# Page settings

baseurl = "http://example.org/"
languageCode = "en-us"
title = "Olena Stefanovska Resume"
theme = "orbit"
googleAnalytics = "UA-XXXXXXX-Y"

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

[params]

## Meta
#    description = "Hugo Responsive Resume/CV Theme for Developers"
#    author = "Pavel Kanyshev"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Olena Stefanovska"
        tagline = "PM/BA"
        avatar = "profile.png"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto: olena.stefanovska@gmail.com"
        title = "olena.stefanovska@gmail.com"

        [[params.contact.list]]
        class = "phone"
        icon = "fa-phone"
        url = "tel:+380938081749"
        title = "+380938081749"

#        [[params.contact.list]]
#        class = "website"
#        icon = "fa-globe"
#        url = "//portfoliosite.com"
#        title = "portfoliosite.com"

        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
        url = "//linkedin.com/in/ostefanovska/"
        title = "linkedin.com/in/ostefanovska"

        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-facebook"
        url = "//fb.com/ostefanovska"
        title = "fb.com/ostefanovska"

        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-skype"
        url = "olena.stefanovska"
        title = "olena.stefanovska"

#        [[params.contact.list]]
#        class = "github"
#        icon = "fa-github"
#        url = "//github.com/username"
#        title = "github.com/username"

#        [[params.contact.list]]
#        class = "twitter"
#        icon = "fa-twitter"
#        url = "//twitter.com/username"
#        title = "@twittername"

    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        degree = "Project management"
        college = "GeekHub courses"
        dates = "2016 - 2017"

        [[params.education.list]]
        degree = "Linguistics (English and German)"
        college = "Cherkasy National University"
        dates = "2009 - 2014"

    # Languages section
    [params.language]
        enable = true
        title = "Languages"

        [[params.language.list]]
        language = "English"
        level = "Advanced"

        [[params.language.list]]
        language = "German"
        level = "Intermediate"

        [[params.language.list]]
        language = "Russian"
        level = "Native"

        [[params.language.list]]
        language = "Ukrainian"
        level = "Native"

    # Interests section
    [params.interests]
        enable = false
        title = "Interests"

        [[params.interests.list]]
        interest = "Climbing"

        [[params.interests.list]]
        interest = "Snowboarding"

        [[params.interests.list]]
        interest = "Cooking"

# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = false
        icon = "fa-user"
        title = "Career Profile"
        summary = "**Summarise your career here** lorem ipsum dolor sit amet, consectetuer adipiscing elit. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu."


    # Skills section
    [params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Skills & Proficiency"

        [[params.skills.list]]
        skill = "Deep understanding of software development methodologies."
        level = "98%"

        [[params.skills.list]]
        skill = "Planning and tracking tasks using Jira&Confluence, Trello, Wrike."
        level = "100%"

        [[params.skills.list]]
        skill = "Project documentation writing."
        level = "47%"

        [[params.skills.list]]
        skill = "Web product, desktop and mobile app testing skills, test case writing."
        level = "95%"

        [[params.skills.list]]
        skill = "Managing product through its entire lifecycle"
        level = "75%"

        [[params.skills.list]]
        skill = "Working across time-zones."
        level = "60%"

        [[params.skills.list]]
        skill = "Wireframing, prototyping, diagram and chart building."
        level = "60%"



    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.jobs.list]]
        position = "Business Analyst"
        dates = "Feb 2018  - Present"
        company = "MEV"
        details = "Managing requirements (gathering, organizing, analysing, validating and verifying). Determining and suggesting potential solutions. Guiding the client, consulting the manager and advising the team. Assisting at various levels of project and helping in task analysis. Creating clear, consistent, unambiguous, complete project documentation. Wireframing, prototyping,UML and BPMN flowcharts building, creating visuals. Jira & Confluence project spaces management."

    # Projects section
    [params.projects]
        enable = false
        icon = "fa-archive"
        title = "Projects"
        intro = "**You can list your side projects or open source libraries in this section.** Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum et ligula in nunc bibendum fringilla a eu lectus"

        [[params.projects.list]]
        title = "Hugrid"
        url = "https://github.com/aerohub/hugrid"
        tagline = "Grid theme for Hugo. It's a kind of boilerplate to perform anyone or anything quickly. Portfolio, collection, bookmarks, contacts and so on"

        [[params.projects.list]]
        title = "Simple FAQ Theme for Hugo"
        url = "https://github.com/aerohub/hugo-faq-theme"
        tagline = "Simple FAQ Theme for Hugo. You may use this theme for building very simple FAQs or note lists."

        [[params.projects.list]]
        title = "Hugo Identity"
        url = "https://github.com/aerohub/hugo-identity-theme"
        tagline = "Little profile/card-style template for Hugo."

        [[params.projects.list]]
        title = "Orbit"
        url = "https://github.com/aerohub/hugo-orbit-theme"
        tagline = "Hugo Resume/CV Theme for Developers."

        [[params.projects.list]]
        title = "Me"
        url = "https://github.com/aerohub/hugo-me-theme"
        tagline = "A simple responsive Hugo theme for personal site."
# Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    #
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
        copyright = ""
